{% set version = "0.5.1" %}
{% set hash_type = "md5" %}
{% set hash_val = "4f09083acd9e6280387833ecfcb56e2c" %}

package:
  name: librosa
  version: {{ version }}

source:
  fn: librosa-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/librosa/librosa-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - audioread >=2.0.0
    - numpy >=1.8.0
    - scipy >=0.13.0
    - scikit-learn >=0.14.0
    - matplotlib >=1.5.0
    - joblib >=0.7.0
    - decorator >=3.0.0
    - six >=1.3
    - resampy >=0.1.2

  run:
    - python
    - setuptools  # necessary for pkg_resources
    - audioread >=2.0.0
    - numpy >=1.8.0
    - scipy >=0.13.0
    - scikit-learn >=0.14.0
    - matplotlib >=1.5.0
    - joblib >=0.7.0
    - decorator >=3.0.0
    - six >=1.3
    - resampy >=0.1.2

test:
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util
    - librosa.display

about:
  home: http://github.com/librosa/librosa
  license: ISC
  summary: 'Python module for audio and music processing'

extra:
  recipe-maintainers:
    - bmcfee
