{% set version = "0.8.1" %}
{% set hash_val = "f2ea5cd26574e58d7ea0c24dbeea25de" %}

package:
  name: librosa
  version: {{ version }}

source:
  fn: librosa-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/librosa/librosa-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools  # necessary for pkg_resources
    - audioread >=2.0.0
    - numpy >=1.15.0
    - scipy >=1.0.0
    - scikit-learn >=0.14.0,!=0.19.0
    - joblib >=0.14.0
    - matplotlib-base >=1.5.0
    - decorator >=3.0.0
    - resampy >=0.2.2
    - numba >=0.43.0
    - pysoundfile >=0.10.2
    - pooch >=1.0

test:
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util
    - librosa.display

about:
  home: http://github.com/librosa/librosa
  license: ISC
  summary: Python module for audio and music processing

extra:
  recipe-maintainers:
    - bmcfee
