travis:
  secure:
    BINSTAR_TOKEN: xc0aHhIQRZ1gKAQsWgekgaAyO0QE4hWnD02nS8nMpqP1fIHa08H6f5LAzz0V/YuJrU6244RxQmosUvxA1UCEgl5eSzDkzxXUXACw8+OIRVPYZocGXCCaPeXmVGylTwdgHy2LgIE0O/LVaBQX7pperj1n5Ffk/NSd40GrXkbmF5fDnh7yKIIKCSCdVli6vT9hVJdzjdAgNIPc3LKI/XirnzlSE2Mw5CtNn0HA0aTdttfY6+ZGexkptEIL7+ZikMtNpZevRp6wRY5YAEolLdC8PWaSpoKrw9gpkS8ZqrpIP3P4SWzdFmaXcz00bR8ZFKiF407326J8It+P53KQGKRaAxQMePfH4b7qcRDefzYwmC4lbjkfgJwK16fmpXwTxAVwsCHQ4o7h4S17kNmRNMouThgA8jqnw7f/1H03povAzc+/pr1E4nNL8gc+pFygrkxkeBfdGebbCT3wTmlsniJ1x3METo5VGDLTH78Cdp2M9gpsHztCY43zpYQ14Y3jQPJAkPR0UsPhRZaLyX2qLL1Wgl36GJ0PvdLMykp7I4Q7J7+v2h/kS0n9qQy1JGWifSjTQzyz1eea/TKcaqr08zEXUajwdtNnatDlA0KQ325yUfjTp+3Q0PCM6sd0N/NVOQeJWD9K6SuHhWYhyJ6ob4/C1bvzAbLvEAGFrTxEsEn8hBE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
