travis:
  secure:
    BINSTAR_TOKEN: wD41yQUs8t7dJz/mhRp353j7dnjM4AHDz14GkJFS4rNsp9E3dTxUD7yER1uavs9CVzlUdh775/UClFfz2olsZ9YIPAc7NCnB9NUiydKhRxHjmmjUXXHn6YcWWHatvoo2uSHs4W++V428O2aMlod92eBVD0ibr7jhNWaf/RfgdhHS1ycNGmFPs/JFoJyBXlyFK4k433aFBqt1Ne8Zue/26xYJya1l3woMDdYEP1mNE7UM9e8Uz7wzxNkufqkoqLxHofa03UFnqbgYwiNw2DJcX7ESg4+cGdgiEU7e4U7FERfUEvHFmRUv+JqcM7TXr1NkVEgLkajSiT6gDki/FRdhrhSlbiCQOzJDkWJVrguloIO64m93PImlptTSRiMDe3rdCMEcaQ3PfwP4VfDGyor4Z8fEkhabgYtujNpH23/yt43/6nXAxIk75LRd6nTBCQ1eYEyIF5f/oKwRrddvzqwDia4THzJ961Clayd097V4Zx2A0ai/q/pHOPhiKHczVoTaZqj2T1w98Pxd+PX80RrncCgQa+bEbdFh3K5GrO93nzvp+Jzfd8Xpx2Yni85k9D2ijgh0u2XG1MQEjQL78z5hD6CkyQ3iVwAGelDUTewgjPg9opizQdCpEj0ER/olmpOQEPFEyx4XwOiqbLf5QnDpJASW8EMzNIeMhbVtKbYybr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
